---
driver:
  name: vagrant

provisioner:
  name: chef_zero_scheduled_task

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[IIS_GIT_SITE::default]
    attributes:
