name 'IIS_GIT_SITE'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures IIS_GIT_SITE'
long_description 'Installs/Configures IIS_GIT_SITE'
version '0.1.2'
